# Generated by Django 3.2.6 on 2021-08-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lexicalentrie_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicalentrie',
            name='phonetic_spelling',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
