# Generated by Django 3.2.6 on 2021-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lexicalentrie_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicalentrie',
            name='audio_file',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
